version: "3.7"

services:
  yoc:
    build: .
    container_name: yoc_certs
    restart: always
    ports:
      - 2006:8000
    volumes:
      - yocmedia:/home/app/webapp/media
    env_file:
      - .env

volumes:
  yocmedia:

networks:
  yoc_certs:
    driver: bridge