version: "3.7"

services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    networks:
      - yoc_certs
    command: redis-server --appendonly yes

  yoc:
    build: .
    container_name: yoc_certs
    restart: always
    ports:
      - 2006:8000
    volumes:
      - yocmedia:/home/app/webapp/media

volumes:
  yocmedia: